MyCrud/Controllers/OsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyCrud;

namespace MyCrud.Controllers
{
    public class OsController : Controller
    {
        public ActionResult Index(string msn, string tipo)
        {
            ViewBag.msn = msn;
            ViewBag.tipo = tipo;
            MyCrudEntities entity = new MyCrudEntities();
            List<OS> objs = entity.OS.ToList();
            return View(objs);
        }

        public ActionResult Novo()
        {
            MyCrudEntities entity = new MyCrudEntities();
            @ViewBag.servicos = entity.SERVICO.ToList();
            OS os = (OS)Session["OS"];
            return View(os);
        }
        public ActionResult AdicionarServico(int Id)
        {
            OS_SERVICO obj = new OS_SERVICO();
            MyCrudEntities entity = new MyCrudEntities();

            obj.SERVICO = (from d in entity.SERVICO where d.ID == Id select d).FirstOrDefault();
            OS os = (OS)Session["OS"];

            if (os == null)
                os = new OS();
            if (obj != null)
                os.OS_SERVICO.Add(obj);
            Session["OS"] = os;
            @ViewBag.servicos = entity.SERVICO.ToList();
            return RedirectToAction("Novo");
        }
        [HttpPost]
        public ActionResult Criar(OS obj)
        {
            try
            {
                MyCrudEntities entity = new MyCrudEntities();
                entity.OS.Add(obj);
                entity.SaveChanges();

                OS os = (OS)Session["OS"];

                foreach (OS_SERVICO item in os.OS_SERVICO)
                    entity.OS_SERVICO.Add(new OS_SERVICO() { ID_SERVICO = item.SERVICO.ID, ID_OS = obj.ID });
                entity.SaveChanges();
                Session["OS"] = null;
                return RedirectToAction("Index", new { msn = "Ordem de servico criada com sucesso!", tipo = "success" });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { msn = "Falha ao criar ordem de servico!", tipo = "danger" });
            }
        }
        public ActionResult Detalhes(int Id)
        {
            MyCrudEntities entity = new MyCrudEntities();
            OS obj = (from d in entity.OS where d.ID == Id select d).FirstOrDefault();
            obj.OS_SERVICO = (from x in entity.OS_SERVICO where x.ID_OS == Id select x).ToList();
            return View(obj);
        }
    }
}

MyCrud/Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyCrud.Controllers
{
    public class ServicosController : Controller
    {
        public ActionResult Index(string msn, string tipo)
        {
            ViewBag.msn = msn;
            ViewBag.tipo = tipo;
            MyCrudEntities entity = new MyCrudEntities();
            List<SERVICO> objs = entity.SERVICO.ToList();
            return View(objs);
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Criar(SERVICO obj)
        {
            try
            {
                MyCrudEntities entity = new MyCrudEntities();

                entity.SERVICO.Add(obj);
                entity.SaveChanges();

                return RedirectToAction("Index", new { msn = "Servico criado com sucesso!", tipo = "success" });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { msn = "Falha ao criar!", tipo = "danger" });
            }
        }

        public ActionResult Editar(int Id)
        {
            MyCrudEntities entity = new MyCrudEntities();
            SERVICO obj = (from d in entity.SERVICO where d.ID == Id select d).FirstOrDefault();
            return View(obj);
        }
        [HttpPost]
        public ActionResult Salvar(SERVICO obj)
        {
            try
            {
                MyCrudEntities entity = new MyCrudEntities();
                entity.SERVICO.Attach(obj);
                entity.Entry(obj).State = System.Data.EntityState.Modified;
                entity.SaveChanges();
                return RedirectToAction("Index", new { msn = "Servico salvado com sucesso!", tipo = "success" });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { msn = "Falha ao salvar!", tipo = "danger" });
            }
        }
        public ActionResult Detalhes(int Id)
        {
            MyCrudEntities entity = new MyCrudEntities();
            SERVICO obj = (from d in entity.SERVICO where d.ID == Id select d).FirstOrDefault();
            return View(obj);
        }

        public ActionResult Excluir(int Id)
        {
            MyCrudEntities entity = new MyCrudEntities();
            SERVICO obj = (from d in entity.SERVICO where d.ID == Id select d).FirstOrDefault();
            return View(obj);
        }
        [HttpPost]
        public ActionResult ConfirmarExcluir(SERVICO obj)
        {
            try
            {

                MyCrudEntities entity = new MyCrudEntities();
                SERVICO _obj = (from d in entity.SERVICO where d.ID == obj.ID select d).FirstOrDefault();
                if (_obj.OS_SERVICO.Count() > 0)
                    return RedirectToAction("Index", new { msn = "Voce nao pode excluir esse servico, pois ele possui Ordem de Servico!", tipo = "danger" });

                entity = new MyCrudEntities();
                entity.SERVICO.Attach(obj);
                entity.Entry(obj).State = System.Data.EntityState.Deleted;
                entity.SaveChanges();
                return RedirectToAction("Index", new { msn = "Servico excluido com sucesso!", tipo = "success" });
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", new { msn = "Falha na exclusao!", tipo = "danger" });
            }
        }
    }
}

MyCrud/Views/Os/Detalhes.cshtml
@model MyCrud.OS

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><i class="fa fa-bars" aria-hidden="true"></i>&nbsp; Ordem Serviço</h2>

  
     <table class="table">
        <tr>
            <th>DESCRIÇÃO </th>
            <th>VALOR </th>
        </tr>

        @if (Model != null)
        {
            foreach (var item in Model.OS_SERVICO)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SERVICO.DESCRICAO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SERVICO.VALOR)
                </td>
            </tr>
            }
        }

    </table>

      <div class="form-group">
        @Html.LabelFor(model => model.INICIO, new { @class = "control-label"})
         @Html.TextBoxFor(model => model.INICIO, new { @class = "form-control",  @readonly= "readonly" })
        @Html.ValidationMessageFor(model => model.INICIO)
    </div>
  
    <div class="form-group">
        @Html.LabelFor(model => model.FIM)      
        @Html.TextBoxFor(model => model.FIM, new { @class = "form-control",  @readonly= "readonly" })
        @Html.ValidationMessageFor(model => model.FIM)
    </div>   
    <div class="form-group">
        @Html.LabelFor(model => model.COD_EQUIPAMENTO)   
        @Html.TextBoxFor(model => model.COD_EQUIPAMENTO, new { @class = "form-control",  @readonly= "readonly" })
        @Html.ValidationMessageFor(model => model.COD_EQUIPAMENTO)
    </div>
<p>
    @Html.ActionLink("Voltar", "Index")
</p>

MyCrud/Views/Os/Index.cshtml
@model IEnumerable<MyCrud.OS>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><i class="fa fa-bars" aria-hidden="true"></i>&nbsp; Ordem Serviço</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.INICIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FIM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.COD_EQUIPAMENTO)
        </th>
        <th>
            
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.INICIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FIM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.COD_EQUIPAMENTO)
        </td>
        <td>
            @Html.ActionLink("Detalhes", "Detalhes", new { id=item.ID })
        </td>
    </tr>
}

</table>
<a href="/Os/Novo" class="btn btn-primary pull-right"><i class="fa fa-floppy-o" aria-hidden="true"></i>&nbsp; Novo</a>

MyCrud/Views/Os/Novo.cshtml
@model MyCrud.OS

@{
    ViewBag.Title = "Novo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><i class="fa fa-bars" aria-hidden="true"></i>&nbsp; Ordem Serviço</h2>

@using (Html.BeginForm("Criar", "Os"))
{
    @Html.ValidationSummary(true)

    Html.RenderPartial("/Views/Shared/_PartialServico.cshtml");

   

    <div class="form-group">
        @Html.LabelFor(model => model.INICIO, new { @class = "control-label" })
        @Html.TextBoxFor(model => model.INICIO, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.INICIO)
    </div>
  
    <div class="form-group">
        @Html.LabelFor(model => model.FIM)
        @Html.TextBoxFor(model => model.FIM, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.FIM)
    </div>   
    <div class="form-group">
        @Html.LabelFor(model => model.COD_EQUIPAMENTO)
        @Html.TextBoxFor(model => model.COD_EQUIPAMENTO, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.COD_EQUIPAMENTO)
    </div>

     
    <script>
        $(function () {
            $('#INICIO').datepicker({ dateFormat: 'dd/mm/yy' });
            $('#FIM').datepicker({ dateFormat: 'dd/mm/yy' });
        });
    </script>

    <p>

        @Html.ActionLink("Voltar", "Index")
        <button type="submit" class="btn btn-success pull-right" value="Criar"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp; Novo</button>
    </p>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@{
    Html.RenderPartial("/Views/Shared/_PartialModal.cshtml");
}

MyCrud/Views/Servicos/Detalhes.cshtml
@model MyCrud.SERVICO

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2><i class="fa fa-cogs" aria-hidden="true"></i>&nbsp  Serviços</h2>


<div class="form-group">
    @Html.LabelFor(model => model.DESCRICAO, new { @class = "control-label" })
    @Html.TextBoxFor(model => model.DESCRICAO, new { @class = "form-control", @readonly = "readonly" })
    @Html.ValidationMessageFor(model => model.DESCRICAO)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.VALOR, new { @class = "control-label" })
    @Html.TextBoxFor(model => model.VALOR, new { @class = "form-control" , @readonly = "readonly"})
    @Html.ValidationMessageFor(model => model.VALOR)
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.ID }) |
    @Html.ActionLink("Voltar", "Index")
</p>

MyCrud/Views/Servicos/Editar.cshtml
@model MyCrud.SERVICO

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2><i class="fa fa-cogs" aria-hidden="true"></i>&nbsp  Serviços</h2>

@using (Html.BeginForm("Salvar","Servicos")) {
    @Html.ValidationSummary(true)


        @Html.HiddenFor(model => model.ID)

        
        <div class="form-group">
            @Html.LabelFor(model => model.DESCRICAO, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.DESCRICAO, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DESCRICAO)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.VALOR, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.VALOR, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VALOR)
        </div>
       
        <p>
             @Html.ActionLink("Voltar", "Index")
            <button type="submit" class="btn btn-success pull-right pull-right"value="Save" ><i class="fa fa-floppy-o" aria-hidden="true"></i>&nbsp; Salvar</button>
        </p>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyCrud/Views/Servicos/Excluir.cshtml
@model MyCrud.SERVICO

@{
    ViewBag.Title = "Excluir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("ConfirmarExcluir", "Servicos"))
{
     @Html.HiddenFor(model => model.ID)
<h2><i class="fa fa-cogs" aria-hidden="true"></i>&nbsp  Serviços</h2>

<h3>Você tem certeza que deseja excluir?</h3>
<div class="form-group">
    @Html.LabelFor(model => model.DESCRICAO, new { @class = "control-label" })
    @Html.TextBoxFor(model => model.DESCRICAO, new { @class = "form-control", @readonly = "readonly" })
    @Html.ValidationMessageFor(model => model.DESCRICAO)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.VALOR, new { @class = "control-label" })
    @Html.TextBoxFor(model => model.VALOR, new { @class = "form-control", @readonly = "readonly" })
    @Html.ValidationMessageFor(model => model.VALOR)
</div>

    <p>
        @Html.ActionLink("Voltar", "Index")
        <button type="submit" value="Delete" class="btn btn-danger pull-right"><i class="fa fa-trash" aria-hidden="true"></i>&nbsp; Confirmar</button>

    </p>
}

MyCrud/Views/Servicos/Index.cshtml
@model IEnumerable<MyCrud.SERVICO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><i class="fa fa-cogs" aria-hidden="true"></i>&nbsp  Serviços</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DESCRICAO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VALOR)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DESCRICAO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VALOR)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.ID }) |
            @Html.ActionLink("Detalhes", "Detalhes", new { id=item.ID }) |
            @Html.ActionLink("Excluir", "Excluir", new { id=item.ID })
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Novo", "Novo")
</p>

MyCrud/Views/Servicos/Novo.cshtml
@model MyCrud.SERVICO

@{
    ViewBag.Title = "Novo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2><i class="fa fa-cogs" aria-hidden="true"></i>&nbsp  Serviços</h2>

@using (Html.BeginForm("Criar", "Servicos"))
{
    @Html.ValidationSummary(true)

     
        <div class="form-group">
            @Html.LabelFor(model => model.DESCRICAO, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.DESCRICAO, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DESCRICAO)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VALOR, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.VALOR, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VALOR)
        </div>
       
        <p>
           @Html.ActionLink("Voltar", "Index")
            <button type="submit" class="btn btn-success pull-right" value="Criar" ><i class="fa fa-plus" aria-hidden="true"></i>&nbsp; Novo</button>
        </p>
        
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MyCrud</title>

    <link href="/fonts/font_glyphicons.css" rel="stylesheet" />
    <link href="/Content/bootstrap.css" rel="stylesheet" />
    <link href="/Content/jquery-ui.css" rel="stylesheet" />
    <script src="/Scripts/jquery-1.12.4.js"></script>
    <script src="/Scripts/jquery-ui.js"></script>
    <script src="/Scripts/bootstrap.min.js"></script>
    <link href="/Content/dashboard.css" rel="stylesheet" /> 
    <script src="~/Scripts/sweetalert.js"></script>
    <link href="~/Content/sweetalert.css" rel="stylesheet" />
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
</head>


  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">MyCrud</a>
        </div>
       
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/Os">Ordem Serviço <span class="sr-only">(current)</span></a></li>
            <li><a href="/Servicos">Serviços</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
         

             @RenderBody()
          <div class="table-responsive"></div>
      </div>
    </div>

    @RenderSection("scripts", required: false)
  </body>
</html>



<script>
    var tipo = "@ViewBag.tipo";
    var msn = "@ViewBag.msn";
    if (tipo == "success") {
        swal("Sucesso!", msn, "success")
    }
    else if (tipo == "danger")
    {
             swal("Falha!", msn, "error")
    }
</script>

MyCrud/Views/Shared/_PartialModal.cshtml
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Serviços</h4>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>DESCRIÇÃO  </th>
                            <th>VALOR </th>
                            <th class="col-md-1"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (@ViewBag.servicos != null)
                        {
                            foreach (var item in (IEnumerable<MyCrud.SERVICO>)@ViewBag.servicos)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DESCRICAO)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.VALOR)
                                </td>
                                <td>
                                    @Html.ActionLink("Selecionar", "AdicionarServico", new { id = item.ID })
                                </td>
                            </tr>
                            }
                        }

                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

MyCrud/Views/Shared/_PartialServico.cshtml
@model MyCrud.OS

 <table class="table">
        <tr>
            <th>DESCRIÇÃO </th>
            <th>VALOR </th>
            <th class="col-md-1">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg" value="Adicionar">Adicionar</button></th>
        </tr>

        @if (Model != null)
        {
            foreach (var item in Model.OS_SERVICO)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SERVICO.DESCRICAO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SERVICO.VALOR)
                </td>
                <td>
                    @Html.ActionLink("Excluir", "Excluir", new { id = item.SERVICO.ID })
                </td>
            </tr>
            }
        }

    </table>